export const dynamic = "force-dynamic";

export async function GET(request: Request) {
  const origin = new URL(request.url).origin;
  const script = `(function(){
var current=document.currentScript,slug=current&&current.getAttribute('data-site');
if(!slug||document.getElementById('webplug-accessibility-host'))return;
var api='${origin}',storeKey='webplug-accessibility:'+slug,state={textSize:0,contrast:false,grayscale:false,highlightLinks:false,readableFont:false,reducedMotion:false,lineHeight:false,textSpacing:false,largeCursor:false},lang=(document.documentElement.lang||'en').toLowerCase().startsWith('ar')?'ar':'en';
try{state=Object.assign(state,JSON.parse(localStorage.getItem(storeKey)||'{}'));}catch(e){}
var labels={en:{reset:'Reset',close:'Close',textSize:'Text size',contrast:'High contrast',grayscale:'Grayscale',highlightLinks:'Highlight links',readableFont:'Readable font',reducedMotion:'Reduce motion',lineHeight:'Line height',textSpacing:'Text spacing',largeCursor:'Large cursor',on:'On',off:'Off'},ar:{reset:'إعادة ضبط',close:'إغلاق',textSize:'حجم النص',contrast:'تباين عالٍ',grayscale:'تدرج رمادي',highlightLinks:'تمييز الروابط',readableFont:'خط سهل القراءة',reducedMotion:'تقليل الحركة',lineHeight:'تباعد الأسطر',textSpacing:'تباعد النص',largeCursor:'مؤشر كبير',on:'مفعل',off:'متوقف'}};
var host=document.createElement('div');host.id='webplug-accessibility-host';host.style.cssText='position:fixed;z-index:2147482998;bottom:18px;';document.body.appendChild(host);var shadow=host.attachShadow({mode:'open'});
var pageStyle=document.createElement('style');pageStyle.id='webplug-accessibility-page-styles';pageStyle.textContent='html[data-wa-text="1"]{font-size:112.5%!important}html[data-wa-text="2"]{font-size:125%!important}html[data-wa-text="3"]{font-size:137.5%!important}html[data-wa-contrast="1"]{filter:contrast(1.4)!important}html[data-wa-gray="1"]{filter:grayscale(1)!important}html[data-wa-contrast="1"][data-wa-gray="1"]{filter:contrast(1.4) grayscale(1)!important}html[data-wa-links="1"] a{text-decoration:underline!important;text-decoration-thickness:3px!important;outline:2px solid #ffbf00!important;outline-offset:2px!important}html[data-wa-font="1"],html[data-wa-font="1"] *{font-family:Arial,Verdana,sans-serif!important}html[data-wa-motion="1"] *,html[data-wa-motion="1"] *:before,html[data-wa-motion="1"] *:after{animation:none!important;transition:none!important;scroll-behavior:auto!important}html[data-wa-line="1"] *{line-height:1.8!important}html[data-wa-spacing="1"] *{letter-spacing:.08em!important;word-spacing:.16em!important}html[data-wa-cursor="1"],html[data-wa-cursor="1"] *{cursor:crosshair!important}';document.head.appendChild(pageStyle);
function esc(v){return String(v).replace(/[&<>\"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]});}
function apply(){var root=document.documentElement;root.dataset.waText=String(state.textSize||0);[['contrast','waContrast'],['grayscale','waGray'],['highlightLinks','waLinks'],['readableFont','waFont'],['reducedMotion','waMotion'],['lineHeight','waLine'],['textSpacing','waSpacing'],['largeCursor','waCursor']].forEach(function(x){root.dataset[x[1]]=state[x[0]]?'1':'0'});try{localStorage.setItem(storeKey,JSON.stringify(state));}catch(e){}renderTools();}
function icon(name){if(name==='eye')return '<svg viewBox="0 0 24 24"><path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.8"/></svg>';if(name==='settings')return '<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3A1.7 1.7 0 0 0 10 3V2.8h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/></svg>';return '<svg viewBox="0 0 24 24"><circle cx="12" cy="4" r="2"/><path d="M5 8h14M12 6v6m0 0-4 9m4-9 4 9m-8-8 4 3 4-3"/></svg>';}
function isOn(key){return key==='textSize'?state.textSize>0:!!state[key]}
var config,open=false;
function renderTools(){if(!config)return;var box=shadow.querySelector('.wa-tools'),l=labels[lang];if(!box)return;box.innerHTML='';Object.keys(config.tools).forEach(function(key){if(!config.tools[key])return;var button=document.createElement('button');var value=key==='textSize'?(state.textSize?String(Math.round(100+state.textSize*12.5))+'%':'100%'):(isOn(key)?l.on:l.off);button.className=isOn(key)?'active':'';button.innerHTML='<span class="wa-tool-icon">'+toolIcon(key)+'</span><span>'+esc(l[key]||key)+'</span><b>'+esc(value)+'</b>';button.onclick=function(){if(key==='textSize')state.textSize=(state.textSize+1)%4;else state[key]=!state[key];apply()};box.appendChild(button);});}
function toolIcon(key){var map={textSize:'A+',contrast:'◐',grayscale:'◑',highlightLinks:'↗',readableFont:'Aa',reducedMotion:'◌',lineHeight:'↕',textSpacing:'↔',largeCursor:'➤'};return map[key]||'•'}
fetch(api+'/api/public/accessibility/'+encodeURIComponent(slug)).then(function(r){if(!r.ok)throw Error();return r.json()}).then(function(data){config=data.config;host.style[config.position==='bottom-left'?'left':'right']='18px';shadow.innerHTML='<style>:host{all:initial}.wa-root{--p:'+esc(config.primaryColor)+';--a:'+esc(config.accentColor)+';font-family:Arial,Tahoma,sans-serif;color:#17211b}.wa-launch{width:58px;height:58px;border:0;border-radius:18px;background:var(--p);color:var(--a);display:grid;place-items:center;box-shadow:0 12px 40px #0003;cursor:pointer}.wa-launch svg{width:29px;fill:none;stroke:currentColor;stroke-width:1.8;stroke-linecap:round;stroke-linejoin:round}.wa-panel{display:none;position:absolute;bottom:70px;width:350px;max-height:min(620px,calc(100vh - 100px));overflow:auto;background:#fff;border:1px solid #dfe2d9;border-radius:20px;box-shadow:0 22px 80px #0c161029}.left{left:0}.right{right:0}.wa-panel.open{display:block}.wa-head{background:var(--p);color:#fff;padding:18px;display:flex;align-items:center;justify-content:space-between}.wa-head h2{font-size:17px;margin:0}.wa-head button{border:0;background:transparent;color:#fff;font-size:22px;cursor:pointer}.wa-tools{padding:12px;display:grid;grid-template-columns:1fr 1fr;gap:8px}.wa-tools button{min-height:94px;border:1px solid #e1e4dc;background:#f8f8f4;border-radius:13px;padding:12px;text-align:start;display:flex;flex-direction:column;gap:7px;cursor:pointer;color:#17211b}.wa-tools button.active{background:color-mix(in srgb,var(--a) 28%,white);border-color:var(--a)}.wa-tool-icon{font-weight:900;font-size:19px}.wa-tools button span:nth-child(2){font-size:12px;font-weight:700}.wa-tools b{font-size:10px;color:#667068;margin-top:auto}.wa-foot{padding:0 12px 13px;display:flex;gap:8px}.wa-foot button{flex:1;border:1px solid #dfe2d9;background:white;border-radius:10px;padding:9px;font-size:11px;font-weight:700;cursor:pointer}[dir=rtl]{direction:rtl}.wa-note{text-align:center;font-size:9px;color:#8a928d;padding-bottom:10px}@media(max-width:400px){.wa-panel{width:calc(100vw - 30px)}.wa-tools{grid-template-columns:1fr 1fr}}</style><div class="wa-root" dir="'+(lang==='ar'?'rtl':'ltr')+'"><section class="wa-panel '+(config.position==='bottom-left'?'left':'right')+'"><header class="wa-head"><h2></h2><button aria-label="Close">×</button></header><div class="wa-tools"></div><div class="wa-foot"><button class="wa-reset"></button></div><div class="wa-note">WebPlug accessibility</div></section><button class="wa-launch" aria-label="Accessibility">'+icon(config.launcherIcon)+'</button></div>';wire();apply()}).catch(function(){});
function wire(){var panel=shadow.querySelector('.wa-panel'),root=shadow.querySelector('.wa-root'),l=labels[lang];root.dir=lang==='ar'?'rtl':'ltr';shadow.querySelector('.wa-head h2').textContent=lang==='ar'?config.titleAr:config.title;shadow.querySelector('.wa-reset').textContent=l.reset;shadow.querySelector('.wa-launch').onclick=function(){open=!open;panel.classList.toggle('open',open)};shadow.querySelector('.wa-head button').onclick=function(){open=false;panel.classList.remove('open')};shadow.querySelector('.wa-reset').onclick=function(){Object.keys(state).forEach(function(k){state[k]=k==='textSize'?0:false});apply()};renderTools()}
window.addEventListener('webplug:language',function(e){lang=e.detail&&e.detail.language==='ar'?'ar':'en';if(config)wire()});
})();`;
  return new Response(script, { headers: { "content-type": "application/javascript; charset=utf-8", "cache-control": "public, max-age=300", "access-control-allow-origin": "*" } });
}
