"use client";

import { useState } from "react";
import { Accessibility, Eye, Save, Settings } from "lucide-react";
import type { AccessibilityConfig, AccessibilityTool } from "@/lib/types";

const tools: Array<[AccessibilityTool, string, string]> = [
  ["textSize", "Text size", "Increase or decrease page text"], ["contrast", "High contrast", "Strengthen foreground contrast"], ["grayscale", "Grayscale", "Remove color from the page"], ["highlightLinks", "Highlight links", "Make interactive links easier to find"], ["readableFont", "Readable font", "Use a clear sans-serif typeface"], ["reducedMotion", "Reduce motion", "Disable animations and transitions"], ["lineHeight", "Line height", "Add more vertical reading space"], ["textSpacing", "Text spacing", "Increase letter and word spacing"], ["largeCursor", "Large cursor", "Show a larger, high-visibility pointer"]
];
const icons = { accessibility: Accessibility, eye: Eye, settings: Settings };

export function AccessibilityForm({ initial, slug, appUrl }: { initial: AccessibilityConfig; slug: string; appUrl: string }) {
  const [config, setConfig] = useState(initial); const [status, setStatus] = useState("");
  function set<K extends keyof AccessibilityConfig>(key: K, value: AccessibilityConfig[K]) { setConfig(current => ({ ...current, [key]: value })); }
  async function save() { setStatus("Saving…"); const response = await fetch("/api/dashboard/accessibility", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(config) }); setStatus(response.ok ? "Saved" : "Could not save"); }
  const Icon = icons[config.launcherIcon];
  return <div className="split"><section className="card"><div className="grid two"><label className="field">Panel title<input className="input" value={config.title} onChange={e => set("title", e.target.value)} /></label><label className="field">Arabic panel title<input className="input" dir="rtl" value={config.titleAr} onChange={e => set("titleAr", e.target.value)} /></label><label className="field">Launcher icon<select className="select" value={config.launcherIcon} onChange={e => set("launcherIcon", e.target.value as AccessibilityConfig["launcherIcon"])}><option value="accessibility">Accessibility person</option><option value="eye">Eye</option><option value="settings">Settings</option></select></label><label className="field">Position<select className="select" value={config.position} onChange={e => set("position", e.target.value as AccessibilityConfig["position"])}><option value="bottom-left">Bottom left</option><option value="bottom-right">Bottom right</option></select></label><label className="field">Primary color<div className="color-row"><input className="color-input" type="color" value={config.primaryColor} onChange={e => set("primaryColor", e.target.value)} /><input className="input" value={config.primaryColor} onChange={e => set("primaryColor", e.target.value)} /></div></label><label className="field">Accent color<div className="color-row"><input className="color-input" type="color" value={config.accentColor} onChange={e => set("accentColor", e.target.value)} /><input className="input" value={config.accentColor} onChange={e => set("accentColor", e.target.value)} /></div></label></div>
    <div className="section-head"><h2>Available tools</h2><span className="muted" style={{ fontSize: 12 }}>{Object.values(config.tools).filter(Boolean).length} enabled</span></div><div className="tool-grid">{tools.map(([key, title, description]) => <label className="tool-toggle" key={key}><div><strong>{title}</strong><small>{description}</small></div><input type="checkbox" checked={config.tools[key]} onChange={e => set("tools", { ...config.tools, [key]: e.target.checked })} /><span /></label>)}</div><button className="button" style={{ marginTop: 20 }} onClick={save}><Save size={15} />Save tools</button>{status && <span className="pill" style={{ marginLeft: 10 }}>{status}</span>}</section>
    <aside className="preview-frame"><span className="eyebrow">Launcher preview</span><div className="access-preview"><button style={{ background: config.primaryColor, color: config.accentColor }}><Icon size={27} /></button><div><strong>{config.title}</strong><small>{Object.values(config.tools).filter(Boolean).length} visitor controls enabled</small></div></div><div className="card" style={{ marginTop: 20 }}><strong>Embed code</strong><pre className="code" style={{ whiteSpace: "pre-wrap", marginTop: 12 }}>{`<script src="${appUrl}/accessibility.js" data-site="${slug}" defer></script>`}</pre></div></aside></div>;
}
