"use client";

import { useState } from "react";
import { Globe2, Plus, ScanSearch } from "lucide-react";
import Link from "next/link";
import type { Tenant } from "@/lib/types";

export function AdminClient({ tenants, sourceCounts }: { tenants: Tenant[]; sourceCounts: Record<string, number> }) {
  const [creating, setCreating] = useState(false); const [busy, setBusy] = useState(""); const [error, setError] = useState("");
  async function create(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy("create"); setError(""); const values = Object.fromEntries(new FormData(event.currentTarget));
    const response = await fetch("/api/admin/tenants", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(values) }); const data = await response.json();
    if (!response.ok) { setError(data.error); setBusy(""); return; } location.reload();
  }
  async function update(id: string, body: object) { setBusy(id); const response = await fetch("/api/admin/tenants", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id, ...body }) }); if (response.ok) location.reload(); else setBusy(""); }
  function editWebsite(tenant: Tenant) { const websiteUrl = prompt("Customer website URL", tenant.websiteUrl); if (websiteUrl && websiteUrl !== tenant.websiteUrl) update(tenant.id, { websiteUrl }); }
  async function scan(id: string) { setBusy(`scan-${id}`); setError(""); const response = await fetch("/api/admin/scan", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ tenantId: id }) }); const data = await response.json(); if (!response.ok) { setError(data.error); setBusy(""); } else location.reload(); }
  return <>
    <div className="actions" style={{ justifyContent: "flex-end", marginTop: -70, marginBottom: 35 }}><button className="button" onClick={() => setCreating(v => !v)}><Plus size={15} />New customer</button></div>
    {creating && <form className="card" onSubmit={create} style={{ marginBottom: 22 }}><h2>Create customer workspace</h2><div className="grid two" style={{ marginTop: 18 }}><label className="field">Company name<input className="input" name="name" required /></label><label className="field">Installation slug<input className="input" name="slug" pattern="[a-z0-9-]+" placeholder="northstar-studio" required /></label><label className="field">Website URL<input className="input" name="websiteUrl" type="url" placeholder="https://example.com" /></label><label className="field">Owner name<input className="input" name="ownerName" required /></label><label className="field">Owner email<input className="input" name="email" type="email" required /></label><label className="field">Temporary password<input className="input" name="password" type="password" minLength={8} required /></label></div>{error && <div className="error" style={{ marginTop: 14 }}>{error}</div>}<div className="actions" style={{ marginTop: 18 }}><button className="button" disabled={busy === "create"}>{busy === "create" ? "Creating…" : "Create workspace"}</button><button type="button" className="button ghost" onClick={() => setCreating(false)}>Cancel</button></div></form>}
    {error && !creating && <div className="error" style={{ marginBottom: 15 }}>{error}</div>}
    <div className="table-wrap">{tenants.length ? <table><thead><tr><th>Customer</th><th>Website</th><th>Knowledge</th><th>Products</th><th /></tr></thead><tbody>{tenants.map(tenant => <tr key={tenant.id}><td><Link href={`/admin/customers/${tenant.id}`}><strong>{tenant.name}</strong><small className="muted" style={{ display: "block", marginTop: 3 }}>/{tenant.slug}</small></Link></td><td><button onClick={() => editWebsite(tenant)} style={{ border: 0, background: "none", padding: 0, cursor: "pointer", color: "inherit", textAlign: "left" }}>{tenant.websiteUrl ? <span style={{ display: "flex", alignItems: "center", gap: 6 }}><Globe2 size={14} />{new URL(tenant.websiteUrl).hostname}</span> : <span className="muted">Set website</span>}</button></td><td>{sourceCounts[tenant.id] || 0} sources</td><td><div className="actions"><span className={`status ${tenant.enabled ? "" : "failed"}`}>chat {tenant.enabled ? "on" : "off"}</span><span className={`status ${tenant.accessibilityEnabled ? "" : "failed"}`}>accessibility {tenant.accessibilityEnabled ? "on" : "off"}</span></div></td><td><div className="actions"><Link className="button ghost" href={`/admin/customers/${tenant.id}`}>Configure</Link><button className="button ghost" disabled={!!busy} onClick={() => scan(tenant.id)}><ScanSearch size={14} />{busy === `scan-${tenant.id}` ? "Scanning…" : "Scan"}</button><button className={`button ${tenant.enabled ? "danger" : "ghost"}`} disabled={!!busy} onClick={() => update(tenant.id, { enabled: !tenant.enabled })}>Chat {tenant.enabled ? "off" : "on"}</button><button className={`button ${tenant.accessibilityEnabled ? "danger" : "ghost"}`} disabled={!!busy} onClick={() => update(tenant.id, { accessibilityEnabled: !tenant.accessibilityEnabled })}>Access {tenant.accessibilityEnabled ? "off" : "on"}</button></div></td></tr>)}</tbody></table> : <div className="empty">No customers yet.</div>}</div>
  </>;
}
